config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :reports
  root 'application#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :reports
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :users
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # indexアクションを設定, カレンダー
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    logger.debug("miyataaaaaaaaaaa")
    logger.debug(params[:report_id])
    @reports = Report.find(params[:report_id])
    @comments = Comment.where(:reports_id => params[:report_id])
    @comment = Comment.new
    #@reports.comments.build
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @comments.reports_id = params[:report_id]
        format.html { redirect_to '/comments', notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:reports_id, :comment, :commented_user)
    end
end

app/controllers/regist_controller.rb
class RegistController < ApplicationController
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :set_report, only: [:show, :edit, :update, :destroy]
  #

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    #@comment = @reports.comments.build
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to '/comments', notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def daily_reports
    @reports = Report.where( date: '2016-06-23' )
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :date, :y, :w, :t, :draft)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/regist_helper.rb
module RegistHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/application/index.html.erb
<nav id="cal-header">
  <ul>
    <li><a class="btn btn-mid" href="/reports/new" title="本日の日報を作成する。"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 日報作成</a></li>
    <li><a class="btn btn-mid" href="/reports" title="投稿されている日報の一覧"><i class="fa fa-list-alt" aria-hidden="true"></i> 日報一覧</a></li>
  </ul>
</nav>

<div id="calendar"></div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <%= f.hidden_field :reports_id %>

  <div class="field">
    <%= f.label :commented_user %><br>
    <%= f.text_field :commented_user %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>日報閲覧</h1>

<h2><b>y (やったこと)</b></h2>
<div class="rep_y">
<%= @reports.y %>
</div>

<h2><b>w (わかったこと)</b></h2>
<div class="rep_w">
<%= @reports.w %>
</div>

<h2><b>t (次にやること)</b></h2>
<div class="rep_t">
<%= @reports.t %>
</div>


<h4 class="comment_disp">Comments</h4>
<div class="comment_list">
    <div class="comment_head"><b>Name Comment</b></div>
 <%if @comments then %>
 <% @comments.each do |comment| %>
  <div class="comment">
    <span class="comment_name"><%= comment.commented_user %></span>
    <%= comment.comment %>
    <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
    <% end %>
  <%end%>
</div>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reports:</strong>
  <%= @comment.reports_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>Commented user:</strong>
  <%= @comment.commented_user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head><!-- // ヘッダ -->
  <title>日報管理システム</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

  <%= include_gon %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head><!-- // ヘッダ -->


<body><!-- // 本体 -->

<!-- ナビゲーションバー -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <h1 class="navbar-header">
      <a class="navbar-brand" href="/">日報管理システム <i class="fa fa-coffee" aria-hidden="true"></i></a>
    </h1>

    <div class="navbar-text navbar-right">
      <% if user_signed_in? %>
        <strong><%= current_user.email %></strong>
        <%= link_to 'プロフィール編集', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "サインアップ", new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "ログイン", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
    </div>
  </div>
</nav>
<!-- ナビゲーションバー -->

<% if notice %>
<div class="alert alert-success content-block"><%= notice %></div>
<% end %>
<% if alert %>
<div class="alert alert-danger content-block"><%= alert %></div>
<% end %>

<!-- コンテンツ -->
<div class="container panel content-block" id="body">
<%= yield %>
</div>
<!-- コンテンツ -->

<!-- フッター -->
<footer class="content-block" id="footer">
  <p>日報管理システム <i class="fa fa-coffee" aria-hidden="true"></i>　&copy; 2016</p>
</footer>
<!-- フッター -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body><!-- // 本体  -->

</html>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :y %><br>
    <%= f.text_area :y %>
  </div>
  <div class="field">
    <%= f.label :w %><br>
    <%= f.text_area :w %>
  </div>
  <div class="field">
    <%= f.label :t %><br>
    <%= f.text_area :t %>
  </div>
  <div class="field">
    <%= f.label :draft %><br>
    <%= f.check_box :draft %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/daily_reports.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Y</th>
      <th>W</th>
      <th>T</th>
      <th>Draft</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.user_id %></td>
        <td><%= report.date %></td>
        <td><%= report.y %></td>
        <td><%= report.w %></td>
        <td><%= report.t %></td>
        <td><%= report.draft %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Y</th>
      <th>W</th>
      <th>T</th>
      <th>Draft</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.user_id %></td>
        <td><%= report.date %></td>
        <td><%= report.y %></td>
        <td><%= report.w %></td>
        <td><%= report.t %></td>
        <td><%= report.draft %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<h2>コメント</h2>
<%= render 'reports/form' %>
<p>
  <strong>ユーザーID番号:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>日付:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>やったこと:</strong>
  <%= @report.y %>
</p>

<p>
  <strong>わかったこと:</strong>
  <%= @report.w %>
</p>

<p>
  <strong>次にやること:</strong>
  <%= @report.t %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @report.draft %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>